<?php
###################### HDFVR Configuration File ######################
$config['connectionstring'] = 'rtmp://pmkfq7.cloud.influxis.com/hdfvr/_definst_';
if(isset($_GET["recorderId"])) { $recorderId = $_GET["recorderId"]; }
$config['languagefile'] = 'translations/en.xml';
$config['qualityurl'] = 'profiles/620x330.xml';
$config['maxRecordingTime'] = 20;
$config['userId']='';
$config['outgoingBuffer']=60;
$config['playbackBuffer']= 1;
$config['autoPlay']='false';
$config['deleteUnsavedFlv'] = 'false';
$config['hideSaveButton']=0;
$config["onSaveSuccessURL"]="";
$config["snapshotSec"] = 5;
$config["snapshotEnable"] = "true";
$config["minRecordTime"] = 5;
$config["backgroundColor"] = 0x990000;
$config["menuColor"] = 0x333333;
$config["radiusCorner"] = 4;
$config["showFps"] = 'true';
$config["recordAgain"] =  'true';
$config["useUserId"] =  'false';
$config["streamPrefix"] = "";
$config["streamName"] = "";
$config["disableAudio"] = 'false';
$config["chmodStreams"] = "";
$config["padding"]=2;
$config["countdownTimer"]="false";
$config["overlayPath"]="fullStar.png";
$config["overlayPosition"]="tr";
$config["loopbackMic"]="false";
$config["showMenu"]="true";
$config["showTimer"] = 'true';
$config["showSoundBar"] = 'true';
echo "donot=removethis";
foreach ($config as $key => $value){
	echo '&'.$key.'='.$value;
}